// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VRCom.proto

#ifndef PROTOBUF_VRCom_2eproto__INCLUDED
#define PROTOBUF_VRCom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace VRCom {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_VRCom_2eproto();
void protobuf_AssignDesc_VRCom_2eproto();
void protobuf_ShutdownFile_VRCom_2eproto();

class Hydra;
class Joystick;
class Mocap;
class MocapSubject;
class Position;
class Rotation;
class Update;

// ===================================================================

class Position : public ::google::protobuf::Message {
 public:
  Position();
  virtual ~Position();

  Position(const Position& from);

  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Position& default_instance();

  void Swap(Position* other);

  // implements Message ----------------------------------------------

  inline Position* New() const { return New(NULL); }

  Position* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Position& from);
  void MergeFrom(const Position& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Position* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:VRCom.Position)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float x_;
  float y_;
  float z_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_VRCom_2eproto();
  friend void protobuf_AssignDesc_VRCom_2eproto();
  friend void protobuf_ShutdownFile_VRCom_2eproto();

  void InitAsDefaultInstance();
  static Position* default_instance_;
};
// -------------------------------------------------------------------

class Rotation : public ::google::protobuf::Message {
 public:
  Rotation();
  virtual ~Rotation();

  Rotation(const Rotation& from);

  inline Rotation& operator=(const Rotation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Rotation& default_instance();

  void Swap(Rotation* other);

  // implements Message ----------------------------------------------

  inline Rotation* New() const { return New(NULL); }

  Rotation* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Rotation& from);
  void MergeFrom(const Rotation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Rotation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // optional float w = 4;
  void clear_w();
  static const int kWFieldNumber = 4;
  float w() const;
  void set_w(float value);

  // @@protoc_insertion_point(class_scope:VRCom.Rotation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_VRCom_2eproto();
  friend void protobuf_AssignDesc_VRCom_2eproto();
  friend void protobuf_ShutdownFile_VRCom_2eproto();

  void InitAsDefaultInstance();
  static Rotation* default_instance_;
};
// -------------------------------------------------------------------

class Joystick : public ::google::protobuf::Message {
 public:
  Joystick();
  virtual ~Joystick();

  Joystick(const Joystick& from);

  inline Joystick& operator=(const Joystick& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Joystick& default_instance();

  void Swap(Joystick* other);

  // implements Message ----------------------------------------------

  inline Joystick* New() const { return New(NULL); }

  Joystick* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Joystick& from);
  void MergeFrom(const Joystick& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Joystick* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:VRCom.Joystick)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float x_;
  float y_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_VRCom_2eproto();
  friend void protobuf_AssignDesc_VRCom_2eproto();
  friend void protobuf_ShutdownFile_VRCom_2eproto();

  void InitAsDefaultInstance();
  static Joystick* default_instance_;
};
// -------------------------------------------------------------------

class MocapSubject : public ::google::protobuf::Message {
 public:
  MocapSubject();
  virtual ~MocapSubject();

  MocapSubject(const MocapSubject& from);

  inline MocapSubject& operator=(const MocapSubject& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MocapSubject& default_instance();

  void Swap(MocapSubject* other);

  // implements Message ----------------------------------------------

  inline MocapSubject* New() const { return New(NULL); }

  MocapSubject* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MocapSubject& from);
  void MergeFrom(const MocapSubject& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MocapSubject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .VRCom.Position pos = 1;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 1;
  const ::VRCom::Position& pos() const;
  ::VRCom::Position* mutable_pos();
  ::VRCom::Position* release_pos();
  void set_allocated_pos(::VRCom::Position* pos);

  // optional .VRCom.Rotation rot = 2;
  bool has_rot() const;
  void clear_rot();
  static const int kRotFieldNumber = 2;
  const ::VRCom::Rotation& rot() const;
  ::VRCom::Rotation* mutable_rot();
  ::VRCom::Rotation* release_rot();
  void set_allocated_rot(::VRCom::Rotation* rot);

  // @@protoc_insertion_point(class_scope:VRCom.MocapSubject)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::VRCom::Position* pos_;
  ::VRCom::Rotation* rot_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_VRCom_2eproto();
  friend void protobuf_AssignDesc_VRCom_2eproto();
  friend void protobuf_ShutdownFile_VRCom_2eproto();

  void InitAsDefaultInstance();
  static MocapSubject* default_instance_;
};
// -------------------------------------------------------------------

class Mocap : public ::google::protobuf::Message {
 public:
  Mocap();
  virtual ~Mocap();

  Mocap(const Mocap& from);

  inline Mocap& operator=(const Mocap& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Mocap& default_instance();

  void Swap(Mocap* other);

  // implements Message ----------------------------------------------

  inline Mocap* New() const { return New(NULL); }

  Mocap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Mocap& from);
  void MergeFrom(const Mocap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Mocap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .VRCom.MocapSubject> subjects = 1;
  int subjects_size() const;
  void clear_subjects();
  static const int kSubjectsFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::VRCom::MocapSubject >&
      subjects() const;
  ::google::protobuf::Map< ::std::string, ::VRCom::MocapSubject >*
      mutable_subjects();

  // @@protoc_insertion_point(class_scope:VRCom.Mocap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::VRCom::MocapSubject,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      Mocap_SubjectsEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::VRCom::MocapSubject,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > subjects_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_VRCom_2eproto();
  friend void protobuf_AssignDesc_VRCom_2eproto();
  friend void protobuf_ShutdownFile_VRCom_2eproto();

  void InitAsDefaultInstance();
  static Mocap* default_instance_;
};
// -------------------------------------------------------------------

class Hydra : public ::google::protobuf::Message {
 public:
  Hydra();
  virtual ~Hydra();

  Hydra(const Hydra& from);

  inline Hydra& operator=(const Hydra& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Hydra& default_instance();

  void Swap(Hydra* other);

  // implements Message ----------------------------------------------

  inline Hydra* New() const { return New(NULL); }

  Hydra* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Hydra& from);
  void MergeFrom(const Hydra& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Hydra* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ctrl_num = 1;
  void clear_ctrl_num();
  static const int kCtrlNumFieldNumber = 1;
  ::google::protobuf::int32 ctrl_num() const;
  void set_ctrl_num(::google::protobuf::int32 value);

  // optional .VRCom.Position pos = 2;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 2;
  const ::VRCom::Position& pos() const;
  ::VRCom::Position* mutable_pos();
  ::VRCom::Position* release_pos();
  void set_allocated_pos(::VRCom::Position* pos);

  // optional .VRCom.Rotation rot = 3;
  bool has_rot() const;
  void clear_rot();
  static const int kRotFieldNumber = 3;
  const ::VRCom::Rotation& rot() const;
  ::VRCom::Rotation* mutable_rot();
  ::VRCom::Rotation* release_rot();
  void set_allocated_rot(::VRCom::Rotation* rot);

  // optional .VRCom.Joystick joy = 4;
  bool has_joy() const;
  void clear_joy();
  static const int kJoyFieldNumber = 4;
  const ::VRCom::Joystick& joy() const;
  ::VRCom::Joystick* mutable_joy();
  ::VRCom::Joystick* release_joy();
  void set_allocated_joy(::VRCom::Joystick* joy);

  // optional float trigger = 5;
  void clear_trigger();
  static const int kTriggerFieldNumber = 5;
  float trigger() const;
  void set_trigger(float value);

  // optional int32 buttons = 6;
  void clear_buttons();
  static const int kButtonsFieldNumber = 6;
  ::google::protobuf::int32 buttons() const;
  void set_buttons(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:VRCom.Hydra)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::VRCom::Position* pos_;
  ::VRCom::Rotation* rot_;
  ::google::protobuf::int32 ctrl_num_;
  float trigger_;
  ::VRCom::Joystick* joy_;
  ::google::protobuf::int32 buttons_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_VRCom_2eproto();
  friend void protobuf_AssignDesc_VRCom_2eproto();
  friend void protobuf_ShutdownFile_VRCom_2eproto();

  void InitAsDefaultInstance();
  static Hydra* default_instance_;
};
// -------------------------------------------------------------------

class Update : public ::google::protobuf::Message {
 public:
  Update();
  virtual ~Update();

  Update(const Update& from);

  inline Update& operator=(const Update& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Update& default_instance();

  enum VrmsgCase {
    kMocap = 1,
    kHydra = 2,
    VRMSG_NOT_SET = 0,
  };

  void Swap(Update* other);

  // implements Message ----------------------------------------------

  inline Update* New() const { return New(NULL); }

  Update* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Update& from);
  void MergeFrom(const Update& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Update* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .VRCom.Mocap mocap = 1;
  bool has_mocap() const;
  void clear_mocap();
  static const int kMocapFieldNumber = 1;
  const ::VRCom::Mocap& mocap() const;
  ::VRCom::Mocap* mutable_mocap();
  ::VRCom::Mocap* release_mocap();
  void set_allocated_mocap(::VRCom::Mocap* mocap);

  // optional .VRCom.Hydra hydra = 2;
  bool has_hydra() const;
  void clear_hydra();
  static const int kHydraFieldNumber = 2;
  const ::VRCom::Hydra& hydra() const;
  ::VRCom::Hydra* mutable_hydra();
  ::VRCom::Hydra* release_hydra();
  void set_allocated_hydra(::VRCom::Hydra* hydra);

  VrmsgCase vrmsg_case() const;
  // @@protoc_insertion_point(class_scope:VRCom.Update)
 private:
  inline void set_has_mocap();
  inline void set_has_hydra();

  inline bool has_vrmsg() const;
  void clear_vrmsg();
  inline void clear_has_vrmsg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  union VrmsgUnion {
    VrmsgUnion() {}
    ::VRCom::Mocap* mocap_;
    ::VRCom::Hydra* hydra_;
  } vrmsg_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_VRCom_2eproto();
  friend void protobuf_AssignDesc_VRCom_2eproto();
  friend void protobuf_ShutdownFile_VRCom_2eproto();

  void InitAsDefaultInstance();
  static Update* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Position

// optional float x = 1;
inline void Position::clear_x() {
  x_ = 0;
}
inline float Position::x() const {
  // @@protoc_insertion_point(field_get:VRCom.Position.x)
  return x_;
}
inline void Position::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Position.x)
}

// optional float y = 2;
inline void Position::clear_y() {
  y_ = 0;
}
inline float Position::y() const {
  // @@protoc_insertion_point(field_get:VRCom.Position.y)
  return y_;
}
inline void Position::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Position.y)
}

// optional float z = 3;
inline void Position::clear_z() {
  z_ = 0;
}
inline float Position::z() const {
  // @@protoc_insertion_point(field_get:VRCom.Position.z)
  return z_;
}
inline void Position::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Position.z)
}

// -------------------------------------------------------------------

// Rotation

// optional float x = 1;
inline void Rotation::clear_x() {
  x_ = 0;
}
inline float Rotation::x() const {
  // @@protoc_insertion_point(field_get:VRCom.Rotation.x)
  return x_;
}
inline void Rotation::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Rotation.x)
}

// optional float y = 2;
inline void Rotation::clear_y() {
  y_ = 0;
}
inline float Rotation::y() const {
  // @@protoc_insertion_point(field_get:VRCom.Rotation.y)
  return y_;
}
inline void Rotation::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Rotation.y)
}

// optional float z = 3;
inline void Rotation::clear_z() {
  z_ = 0;
}
inline float Rotation::z() const {
  // @@protoc_insertion_point(field_get:VRCom.Rotation.z)
  return z_;
}
inline void Rotation::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Rotation.z)
}

// optional float w = 4;
inline void Rotation::clear_w() {
  w_ = 0;
}
inline float Rotation::w() const {
  // @@protoc_insertion_point(field_get:VRCom.Rotation.w)
  return w_;
}
inline void Rotation::set_w(float value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Rotation.w)
}

// -------------------------------------------------------------------

// Joystick

// optional float x = 1;
inline void Joystick::clear_x() {
  x_ = 0;
}
inline float Joystick::x() const {
  // @@protoc_insertion_point(field_get:VRCom.Joystick.x)
  return x_;
}
inline void Joystick::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Joystick.x)
}

// optional float y = 2;
inline void Joystick::clear_y() {
  y_ = 0;
}
inline float Joystick::y() const {
  // @@protoc_insertion_point(field_get:VRCom.Joystick.y)
  return y_;
}
inline void Joystick::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Joystick.y)
}

// -------------------------------------------------------------------

// MocapSubject

// optional .VRCom.Position pos = 1;
inline bool MocapSubject::has_pos() const {
  return !_is_default_instance_ && pos_ != NULL;
}
inline void MocapSubject::clear_pos() {
  if (GetArenaNoVirtual() == NULL && pos_ != NULL) delete pos_;
  pos_ = NULL;
}
inline const ::VRCom::Position& MocapSubject::pos() const {
  // @@protoc_insertion_point(field_get:VRCom.MocapSubject.pos)
  return pos_ != NULL ? *pos_ : *default_instance_->pos_;
}
inline ::VRCom::Position* MocapSubject::mutable_pos() {
  
  if (pos_ == NULL) {
    pos_ = new ::VRCom::Position;
  }
  // @@protoc_insertion_point(field_mutable:VRCom.MocapSubject.pos)
  return pos_;
}
inline ::VRCom::Position* MocapSubject::release_pos() {
  
  ::VRCom::Position* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void MocapSubject::set_allocated_pos(::VRCom::Position* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:VRCom.MocapSubject.pos)
}

// optional .VRCom.Rotation rot = 2;
inline bool MocapSubject::has_rot() const {
  return !_is_default_instance_ && rot_ != NULL;
}
inline void MocapSubject::clear_rot() {
  if (GetArenaNoVirtual() == NULL && rot_ != NULL) delete rot_;
  rot_ = NULL;
}
inline const ::VRCom::Rotation& MocapSubject::rot() const {
  // @@protoc_insertion_point(field_get:VRCom.MocapSubject.rot)
  return rot_ != NULL ? *rot_ : *default_instance_->rot_;
}
inline ::VRCom::Rotation* MocapSubject::mutable_rot() {
  
  if (rot_ == NULL) {
    rot_ = new ::VRCom::Rotation;
  }
  // @@protoc_insertion_point(field_mutable:VRCom.MocapSubject.rot)
  return rot_;
}
inline ::VRCom::Rotation* MocapSubject::release_rot() {
  
  ::VRCom::Rotation* temp = rot_;
  rot_ = NULL;
  return temp;
}
inline void MocapSubject::set_allocated_rot(::VRCom::Rotation* rot) {
  delete rot_;
  rot_ = rot;
  if (rot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:VRCom.MocapSubject.rot)
}

// -------------------------------------------------------------------

// Mocap

// map<string, .VRCom.MocapSubject> subjects = 1;
inline int Mocap::subjects_size() const {
  return subjects_.size();
}
inline void Mocap::clear_subjects() {
  subjects_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::VRCom::MocapSubject >&
Mocap::subjects() const {
  // @@protoc_insertion_point(field_map:VRCom.Mocap.subjects)
  return subjects_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::VRCom::MocapSubject >*
Mocap::mutable_subjects() {
  // @@protoc_insertion_point(field_mutable_map:VRCom.Mocap.subjects)
  return subjects_.MutableMap();
}

// -------------------------------------------------------------------

// Hydra

// optional int32 ctrl_num = 1;
inline void Hydra::clear_ctrl_num() {
  ctrl_num_ = 0;
}
inline ::google::protobuf::int32 Hydra::ctrl_num() const {
  // @@protoc_insertion_point(field_get:VRCom.Hydra.ctrl_num)
  return ctrl_num_;
}
inline void Hydra::set_ctrl_num(::google::protobuf::int32 value) {
  
  ctrl_num_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Hydra.ctrl_num)
}

// optional .VRCom.Position pos = 2;
inline bool Hydra::has_pos() const {
  return !_is_default_instance_ && pos_ != NULL;
}
inline void Hydra::clear_pos() {
  if (GetArenaNoVirtual() == NULL && pos_ != NULL) delete pos_;
  pos_ = NULL;
}
inline const ::VRCom::Position& Hydra::pos() const {
  // @@protoc_insertion_point(field_get:VRCom.Hydra.pos)
  return pos_ != NULL ? *pos_ : *default_instance_->pos_;
}
inline ::VRCom::Position* Hydra::mutable_pos() {
  
  if (pos_ == NULL) {
    pos_ = new ::VRCom::Position;
  }
  // @@protoc_insertion_point(field_mutable:VRCom.Hydra.pos)
  return pos_;
}
inline ::VRCom::Position* Hydra::release_pos() {
  
  ::VRCom::Position* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void Hydra::set_allocated_pos(::VRCom::Position* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:VRCom.Hydra.pos)
}

// optional .VRCom.Rotation rot = 3;
inline bool Hydra::has_rot() const {
  return !_is_default_instance_ && rot_ != NULL;
}
inline void Hydra::clear_rot() {
  if (GetArenaNoVirtual() == NULL && rot_ != NULL) delete rot_;
  rot_ = NULL;
}
inline const ::VRCom::Rotation& Hydra::rot() const {
  // @@protoc_insertion_point(field_get:VRCom.Hydra.rot)
  return rot_ != NULL ? *rot_ : *default_instance_->rot_;
}
inline ::VRCom::Rotation* Hydra::mutable_rot() {
  
  if (rot_ == NULL) {
    rot_ = new ::VRCom::Rotation;
  }
  // @@protoc_insertion_point(field_mutable:VRCom.Hydra.rot)
  return rot_;
}
inline ::VRCom::Rotation* Hydra::release_rot() {
  
  ::VRCom::Rotation* temp = rot_;
  rot_ = NULL;
  return temp;
}
inline void Hydra::set_allocated_rot(::VRCom::Rotation* rot) {
  delete rot_;
  rot_ = rot;
  if (rot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:VRCom.Hydra.rot)
}

// optional .VRCom.Joystick joy = 4;
inline bool Hydra::has_joy() const {
  return !_is_default_instance_ && joy_ != NULL;
}
inline void Hydra::clear_joy() {
  if (GetArenaNoVirtual() == NULL && joy_ != NULL) delete joy_;
  joy_ = NULL;
}
inline const ::VRCom::Joystick& Hydra::joy() const {
  // @@protoc_insertion_point(field_get:VRCom.Hydra.joy)
  return joy_ != NULL ? *joy_ : *default_instance_->joy_;
}
inline ::VRCom::Joystick* Hydra::mutable_joy() {
  
  if (joy_ == NULL) {
    joy_ = new ::VRCom::Joystick;
  }
  // @@protoc_insertion_point(field_mutable:VRCom.Hydra.joy)
  return joy_;
}
inline ::VRCom::Joystick* Hydra::release_joy() {
  
  ::VRCom::Joystick* temp = joy_;
  joy_ = NULL;
  return temp;
}
inline void Hydra::set_allocated_joy(::VRCom::Joystick* joy) {
  delete joy_;
  joy_ = joy;
  if (joy) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:VRCom.Hydra.joy)
}

// optional float trigger = 5;
inline void Hydra::clear_trigger() {
  trigger_ = 0;
}
inline float Hydra::trigger() const {
  // @@protoc_insertion_point(field_get:VRCom.Hydra.trigger)
  return trigger_;
}
inline void Hydra::set_trigger(float value) {
  
  trigger_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Hydra.trigger)
}

// optional int32 buttons = 6;
inline void Hydra::clear_buttons() {
  buttons_ = 0;
}
inline ::google::protobuf::int32 Hydra::buttons() const {
  // @@protoc_insertion_point(field_get:VRCom.Hydra.buttons)
  return buttons_;
}
inline void Hydra::set_buttons(::google::protobuf::int32 value) {
  
  buttons_ = value;
  // @@protoc_insertion_point(field_set:VRCom.Hydra.buttons)
}

// -------------------------------------------------------------------

// Update

// optional .VRCom.Mocap mocap = 1;
inline bool Update::has_mocap() const {
  return vrmsg_case() == kMocap;
}
inline void Update::set_has_mocap() {
  _oneof_case_[0] = kMocap;
}
inline void Update::clear_mocap() {
  if (has_mocap()) {
    delete vrmsg_.mocap_;
    clear_has_vrmsg();
  }
}
inline  const ::VRCom::Mocap& Update::mocap() const {
  // @@protoc_insertion_point(field_get:VRCom.Update.mocap)
  return has_mocap()
      ? *vrmsg_.mocap_
      : ::VRCom::Mocap::default_instance();
}
inline ::VRCom::Mocap* Update::mutable_mocap() {
  if (!has_mocap()) {
    clear_vrmsg();
    set_has_mocap();
    vrmsg_.mocap_ = new ::VRCom::Mocap;
  }
  // @@protoc_insertion_point(field_mutable:VRCom.Update.mocap)
  return vrmsg_.mocap_;
}
inline ::VRCom::Mocap* Update::release_mocap() {
  if (has_mocap()) {
    clear_has_vrmsg();
    ::VRCom::Mocap* temp = vrmsg_.mocap_;
    vrmsg_.mocap_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Update::set_allocated_mocap(::VRCom::Mocap* mocap) {
  clear_vrmsg();
  if (mocap) {
    set_has_mocap();
    vrmsg_.mocap_ = mocap;
  }
  // @@protoc_insertion_point(field_set_allocated:VRCom.Update.mocap)
}

// optional .VRCom.Hydra hydra = 2;
inline bool Update::has_hydra() const {
  return vrmsg_case() == kHydra;
}
inline void Update::set_has_hydra() {
  _oneof_case_[0] = kHydra;
}
inline void Update::clear_hydra() {
  if (has_hydra()) {
    delete vrmsg_.hydra_;
    clear_has_vrmsg();
  }
}
inline  const ::VRCom::Hydra& Update::hydra() const {
  // @@protoc_insertion_point(field_get:VRCom.Update.hydra)
  return has_hydra()
      ? *vrmsg_.hydra_
      : ::VRCom::Hydra::default_instance();
}
inline ::VRCom::Hydra* Update::mutable_hydra() {
  if (!has_hydra()) {
    clear_vrmsg();
    set_has_hydra();
    vrmsg_.hydra_ = new ::VRCom::Hydra;
  }
  // @@protoc_insertion_point(field_mutable:VRCom.Update.hydra)
  return vrmsg_.hydra_;
}
inline ::VRCom::Hydra* Update::release_hydra() {
  if (has_hydra()) {
    clear_has_vrmsg();
    ::VRCom::Hydra* temp = vrmsg_.hydra_;
    vrmsg_.hydra_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Update::set_allocated_hydra(::VRCom::Hydra* hydra) {
  clear_vrmsg();
  if (hydra) {
    set_has_hydra();
    vrmsg_.hydra_ = hydra;
  }
  // @@protoc_insertion_point(field_set_allocated:VRCom.Update.hydra)
}

inline bool Update::has_vrmsg() const {
  return vrmsg_case() != VRMSG_NOT_SET;
}
inline void Update::clear_has_vrmsg() {
  _oneof_case_[0] = VRMSG_NOT_SET;
}
inline Update::VrmsgCase Update::vrmsg_case() const {
  return Update::VrmsgCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace VRCom

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_VRCom_2eproto__INCLUDED
